name: 'pr-comment'
description: 'PR comment actions'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  owner: 
    description: 'Onwer of repo/org'
    required: true
  repo:
    description: "Repo name"
    required: true
  pr_number:
    description: "PR number"
    required: true
  token:
    description: "Github token"
    required: true

runs:
  using: node16
  main: dist/index.js
